# Generated by Django 5.0.3 on 2024-04-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_name_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
    ]
