# Generated by Django 5.0.3 on 2024-04-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_medication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='user',
        ),
    ]
