# Generated by Django 5.0.3 on 2024-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
